# Generated by Django 4.2.7 on 2024-01-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('curd', 'curd'), ('milk', 'milk'), ('milkshake', 'milkshake'), ('paneer', 'paneer'), ('ghee', 'ghee'), ('cheese', 'cheese'), ('icecreams', 'icecreams')], max_length=200)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
